### ISSUE TITLE
DynamoDB ProvisionedThroughputExceededException - DynamoDB auto scale cold start while traffic spike

### ISSUE THREAD

**Issue by ecov-user** [source-cooperative/source.coop#12]
Error Stack: {"level":50,"time":1729982445010,"pid":12,"hostname":"169.254.83.89","err":{"type":"ProvisionedThroughputExceededException","message":"The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API.","stack":"ProvisionedThroughputExceededException: The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API.\n    at de_ProvisionedThroughputExceededExceptionRes (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js:2429:21)\n    at de_CommandError (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js:2140:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /var/task/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20\n    at async /var/task/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/index.js:164:30\n    at async /var/task/node_modules/@smithy/core/dist-cjs/index.js:165:18\n    at async /var/task/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38\n    at async /var/task/node_modules/@aws-sdk/middleware-logger/dis

**Comment by ecov-user** [comment]
DynamoDB Table is configured with RCU 1-10 and WCU 1-25. By the time auto-scale kicks in , traffic is already spiked and causing errors.  Here is an example from 10/26 05:56 AM when auto scaling took more than a minute and 40-50 requests failed during that time.  Setup RCU as 5-10 to take care of the spiky behavior. Will observe errors after the change. 
Errors
![image](https://github.com/user-attachments/assets/b1ed7dd8-0cd1-4c16-b062-e27f1e2914ff)

Auto-scaling Cold Start
![image](https://github.com/user-attachments/assets/3f6045ac-2244-477e-9775-d3612fba9491)

DynamoDB Setup 
![image](https://github.com/user-attachments/assets/334ad1f0-01de-429a-90c8-7750f21c9dad)


fyi @jedsundwall @kbgg @navdeepg2021

**Comment by kbgg** [comment]
This repository is for issues and tasks related to the open-source codebase of the Frontend & API and not the infrastructure. We don't currently have a repository related to infrastructure so this is a great opportunity for you to create one. Here's that I think that repository could contain:

- Tracking of issues related to infrastructure, like this one
- Wiki with guides on how to deploy out Source Cooperative, along with recommendations on settings
- Deployment scripts / infrastructure provisioning tools
  -  I see two options for infrastructure provisioning, Terraform and AWS CloudFormation
  - Terraform would be the better option imo, since we intend to deploy out certain aspects of Source Cooperative (data proxy and buckets) to multiple different cloud providers

**Comment by ecov-user** [comment]
This is taken care already
